/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

/**
 *
 * @author Andre
 */
public class frm_cliente extends javax.swing.JFrame {

    /**
     * frm_cliente
     */
    public frm_cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_cod_cli = new javax.swing.JTextField();
        txt_bairro_cli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_cidade_cli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nome_cli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_end_cli = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_tel_cli = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_cep_cli = new javax.swing.JTextField();
        cbb_estado_cli = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_cliente = new javax.swing.JTable();
        btn_cancelar_cli = new javax.swing.JButton();
        btn_novo_cli = new javax.swing.JButton();
        btn_alterar_cli = new javax.swing.JButton();
        btn_salvar_cli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Código");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 60, 17);

        txt_cod_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_cliActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cod_cli);
        txt_cod_cli.setBounds(10, 30, 80, 30);
        jPanel1.add(txt_bairro_cli);
        txt_bairro_cli.setBounds(440, 90, 240, 30);

        jLabel2.setText("Bairro");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(440, 70, 60, 20);
        jPanel1.add(txt_cidade_cli);
        txt_cidade_cli.setBounds(10, 150, 250, 30);

        jLabel3.setText("Cidade");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 130, 160, 20);

        jLabel4.setText("UF");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 130, 60, 20);
        jPanel1.add(txt_nome_cli);
        txt_nome_cli.setBounds(100, 30, 580, 30);

        jLabel5.setText("Nome");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 10, 70, 20);
        jPanel1.add(txt_end_cli);
        txt_end_cli.setBounds(10, 90, 420, 30);

        jLabel6.setText("Endereço");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 70, 100, 20);

        jLabel7.setText("Telefone");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(470, 130, 110, 20);
        jPanel1.add(txt_tel_cli);
        txt_tel_cli.setBounds(470, 150, 210, 30);

        jLabel8.setText("CEP");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(340, 130, 110, 20);
        jPanel1.add(txt_cep_cli);
        txt_cep_cli.setBounds(340, 150, 120, 30);

        cbb_estado_cli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jPanel1.add(cbb_estado_cli);
        cbb_estado_cli.setBounds(270, 150, 60, 30);

        tb_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOME", "CIDADE", "TELEFONE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_cliente);
        if (tb_cliente.getColumnModel().getColumnCount() > 0) {
            tb_cliente.getColumnModel().getColumn(0).setMinWidth(20);
            tb_cliente.getColumnModel().getColumn(0).setPreferredWidth(15);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 200, 670, 240);

        btn_cancelar_cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/remove.png"))); // NOI18N
        btn_cancelar_cli.setText("Cancelar");
        btn_cancelar_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar_cliActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelar_cli);
        btn_cancelar_cli.setBounds(90, 460, 120, 40);

        btn_novo_cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/cad-adicionar.png"))); // NOI18N
        btn_novo_cli.setText("Novo");
        btn_novo_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo_cliActionPerformed(evt);
            }
        });
        jPanel1.add(btn_novo_cli);
        btn_novo_cli.setBounds(240, 460, 110, 40);

        btn_alterar_cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/cad-editar.png"))); // NOI18N
        btn_alterar_cli.setText("Alterar");
        jPanel1.add(btn_alterar_cli);
        btn_alterar_cli.setBounds(380, 460, 110, 41);

        btn_salvar_cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/accept.png"))); // NOI18N
        btn_salvar_cli.setText("Salvar");
        jPanel1.add(btn_salvar_cli);
        btn_salvar_cli.setBounds(520, 460, 120, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 710, 540);

        setSize(new java.awt.Dimension(728, 578));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cod_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_cliActionPerformed

    private void btn_cancelar_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelar_cliActionPerformed

    private void btn_novo_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_novo_cliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar_cli;
    private javax.swing.JButton btn_cancelar_cli;
    private javax.swing.JButton btn_novo_cli;
    private javax.swing.JButton btn_salvar_cli;
    private javax.swing.JComboBox<String> cbb_estado_cli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_cliente;
    private javax.swing.JTextField txt_bairro_cli;
    private javax.swing.JTextField txt_cep_cli;
    private javax.swing.JTextField txt_cidade_cli;
    private javax.swing.JTextField txt_cod_cli;
    private javax.swing.JTextField txt_end_cli;
    private javax.swing.JTextField txt_nome_cli;
    private javax.swing.JTextField txt_tel_cli;
    // End of variables declaration//GEN-END:variables
}
