/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import controller.ControllerClientes;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ModelClientes;

/**
 *
 * @author Andre
 */
public class frm_cliente extends javax.swing.JFrame {
    
    ControllerClientes controllerCliente = new ControllerClientes();
    ModelClientes modelCliente = new ModelClientes();
    ArrayList<ModelClientes> listaModelClientes = new ArrayList<>();
    String salvarAlterar;
    
    /**
     * frm_cliente
     */
    public frm_cliente() {
        initComponents();
        carregarCliente();
        habilitardDesabilitarCampos(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_cod_cli = new javax.swing.JTextField();
        txt_bairro_cli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_cidade_cli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nome_cli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_end_cli = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbb_uf_cli = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_cliente = new javax.swing.JTable();
        btn_cancelar_cli = new javax.swing.JButton();
        btn_novo_cli = new javax.swing.JButton();
        btn_alterar_cli = new javax.swing.JButton();
        btn_salvar_cli = new javax.swing.JButton();
        btn_excluir_cli = new javax.swing.JButton();
        txt_cep_cli = new javax.swing.JFormattedTextField();
        txt_tel_cli = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Código");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 60, 17);

        txt_cod_cli.setEditable(false);
        txt_cod_cli.setBorder(null);
        txt_cod_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_cliActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cod_cli);
        txt_cod_cli.setBounds(10, 30, 80, 30);
        jPanel1.add(txt_bairro_cli);
        txt_bairro_cli.setBounds(440, 90, 220, 30);

        jLabel2.setText("Bairro");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(440, 70, 60, 20);
        jPanel1.add(txt_cidade_cli);
        txt_cidade_cli.setBounds(10, 150, 250, 30);

        jLabel3.setText("Cidade");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 130, 160, 20);

        jLabel4.setText("UF");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 130, 60, 20);
        jPanel1.add(txt_nome_cli);
        txt_nome_cli.setBounds(100, 30, 560, 30);

        jLabel5.setText("Nome");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 10, 70, 20);
        jPanel1.add(txt_end_cli);
        txt_end_cli.setBounds(10, 90, 420, 30);

        jLabel6.setText("Endereço");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 70, 100, 20);

        jLabel7.setText("Telefone");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(470, 130, 110, 20);

        jLabel8.setText("CEP");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(340, 130, 110, 20);

        cbb_uf_cli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jPanel1.add(cbb_uf_cli);
        cbb_uf_cli.setBounds(270, 150, 60, 30);

        tb_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOME", "CIDADE", "UF", "TELEFONE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_cliente.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tb_cliente);
        if (tb_cliente.getColumnModel().getColumnCount() > 0) {
            tb_cliente.getColumnModel().getColumn(0).setMinWidth(70);
            tb_cliente.getColumnModel().getColumn(0).setPreferredWidth(70);
            tb_cliente.getColumnModel().getColumn(0).setMaxWidth(70);
            tb_cliente.getColumnModel().getColumn(1).setMinWidth(275);
            tb_cliente.getColumnModel().getColumn(1).setPreferredWidth(275);
            tb_cliente.getColumnModel().getColumn(1).setMaxWidth(275);
            tb_cliente.getColumnModel().getColumn(2).setMinWidth(130);
            tb_cliente.getColumnModel().getColumn(2).setPreferredWidth(130);
            tb_cliente.getColumnModel().getColumn(2).setMaxWidth(130);
            tb_cliente.getColumnModel().getColumn(3).setMinWidth(50);
            tb_cliente.getColumnModel().getColumn(3).setPreferredWidth(50);
            tb_cliente.getColumnModel().getColumn(3).setMaxWidth(50);
            tb_cliente.getColumnModel().getColumn(4).setMinWidth(130);
            tb_cliente.getColumnModel().getColumn(4).setPreferredWidth(130);
            tb_cliente.getColumnModel().getColumn(4).setMaxWidth(130);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 200, 650, 170);

        btn_cancelar_cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/Cancelar (1).png"))); // NOI18N
        btn_cancelar_cli.setText("Cancelar");
        btn_cancelar_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar_cliActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelar_cli);
        btn_cancelar_cli.setBounds(10, 390, 120, 40);

        btn_novo_cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/Adicionar (1).png"))); // NOI18N
        btn_novo_cli.setText("Novo");
        btn_novo_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo_cliActionPerformed(evt);
            }
        });
        jPanel1.add(btn_novo_cli);
        btn_novo_cli.setBounds(400, 390, 120, 40);

        btn_alterar_cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/page_edit.png"))); // NOI18N
        btn_alterar_cli.setText("Alterar");
        btn_alterar_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterar_cliActionPerformed(evt);
            }
        });
        jPanel1.add(btn_alterar_cli);
        btn_alterar_cli.setBounds(270, 390, 120, 40);

        btn_salvar_cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/Salvar (1).png"))); // NOI18N
        btn_salvar_cli.setText("Salvar");
        btn_salvar_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar_cliActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salvar_cli);
        btn_salvar_cli.setBounds(530, 390, 130, 40);

        btn_excluir_cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/Excluir (1).png"))); // NOI18N
        btn_excluir_cli.setText("Excluir");
        btn_excluir_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_cliActionPerformed(evt);
            }
        });
        jPanel1.add(btn_excluir_cli);
        btn_excluir_cli.setBounds(140, 390, 120, 40);

        try {
            txt_cep_cli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txt_cep_cli);
        txt_cep_cli.setBounds(340, 150, 120, 30);

        try {
            txt_tel_cli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txt_tel_cli);
        txt_tel_cli.setBounds(470, 150, 190, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 440);

        setSize(new java.awt.Dimension(686, 478));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cod_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_cliActionPerformed

    private void btn_cancelar_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar_cliActionPerformed
        // Cancelar cadastro
        habilitardDesabilitarCampos(false);
        limparCampos();
    }//GEN-LAST:event_btn_cancelar_cliActionPerformed

    private void btn_novo_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo_cliActionPerformed
        // Novo cadastro de cliente.
        habilitardDesabilitarCampos(true);
        salvarAlterar = "salvar";
    }//GEN-LAST:event_btn_novo_cliActionPerformed

    private void btn_salvar_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar_cliActionPerformed
        // Salvar cliente
        if(salvarAlterar.equals("salvar")){
        modelCliente.setNome_cli(this.txt_nome_cli.getText());
        modelCliente.setEndereco_cli(this.txt_end_cli.getText());
        modelCliente.setBairro_cli(this.txt_bairro_cli.getText());
        modelCliente.setCidade_cli(this.txt_cidade_cli.getText());
        modelCliente.setUf_cli(this.cbb_uf_cli.getSelectedItem().toString());
        modelCliente.setCep_cli(this.txt_cep_cli.getText());
        modelCliente.setTelefone_cli(this.txt_tel_cli.getText());
        
        if(controllerCliente.salvarclienteController(modelCliente)>0){
            JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso ! ","ATENÇÃO",JOptionPane.WARNING_MESSAGE);
            this.carregarCliente();
            this.limparCampos();
            this.habilitardDesabilitarCampos(false);
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar o cliente !","ERRO", JOptionPane.ERROR_MESSAGE);
        } 
        //Alterar cliente
        }else{
        modelCliente.setId_cliente(Integer.parseInt(this.txt_cod_cli.getText()));
        modelCliente.setNome_cli(this.txt_nome_cli.getText());
        modelCliente.setEndereco_cli(this.txt_end_cli.getText());
        modelCliente.setBairro_cli(this.txt_bairro_cli.getText());
        modelCliente.setCidade_cli(this.txt_cidade_cli.getText());
        modelCliente.setUf_cli(this.cbb_uf_cli.getSelectedItem().toString());
        modelCliente.setCep_cli(this.txt_cep_cli.getText());
        modelCliente.setTelefone_cli(this.txt_tel_cli.getText());
        
        if(controllerCliente.atualizarclienteController(modelCliente)){
            JOptionPane.showMessageDialog(this, "Cliente alterado com sucesso ! ","ATENÇÃO",JOptionPane.WARNING_MESSAGE);
            this.carregarCliente();
            this.limparCampos();
            this.habilitardDesabilitarCampos(false);
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao alterar o cliente !","ERRO", JOptionPane.ERROR_MESSAGE);
        }      
        } 
    }//GEN-LAST:event_btn_salvar_cliActionPerformed

    private void btn_excluir_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_cliActionPerformed
        // Excluir um cliente do banco de dados.
        int linha = tb_cliente.getSelectedRow();
        int codigoCliente = (int) tb_cliente.getValueAt(linha, 0);
        
        if (controllerCliente.excluirclienteController(codigoCliente)){
            JOptionPane.showMessageDialog(this, "Cliente excluido com sucesso !","ATENÇÃO",JOptionPane.WARNING_MESSAGE);
            this.carregarCliente();
        }else{
            JOptionPane.showConfirmDialog(this, "Erro ao excluir Cliente !","ERRO", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_btn_excluir_cliActionPerformed

    private void btn_alterar_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterar_cliActionPerformed
        // TODO add your handling code here:
        // Alterando cadastro de produtos
        
        this.habilitardDesabilitarCampos(true);
        
        int linha = this.tb_cliente.getSelectedRow();        
        try {
        int codigoCliente = (int) this.tb_cliente.getValueAt(linha, 0);
        salvarAlterar = "alterar";
            //Recuperar dados do banco
            modelCliente = controllerCliente.getClienteController(codigoCliente);
            //Setar na interface
           this.txt_cod_cli.setText(String.valueOf(modelCliente.getId_cliente()));
           this.txt_nome_cli.setText(modelCliente.getNome_cli());
           this.txt_end_cli.setText(String.valueOf(modelCliente.getEndereco_cli()));
           this.txt_bairro_cli.setText(String.valueOf(modelCliente.getBairro_cli()));            
           this.txt_cidade_cli.setText(String.valueOf(modelCliente.getCidade_cli()));            
           this.cbb_uf_cli.setSelectedItem(String.valueOf(modelCliente.getUf_cli())); 
           this.txt_cep_cli.setText(String.valueOf(modelCliente.getCep_cli()));
           this.txt_tel_cli.setText(String.valueOf(modelCliente.getTelefone_cli()));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, " Código inválido ou nenhum registro selecionado "," Aviso ! ",JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_btn_alterar_cliActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_cliente().setVisible(true);
            }
        });
    }
    
    //HABILITAR E DESABILITAR CAMPOS
    private void habilitardDesabilitarCampos(boolean condicao){
        txt_cod_cli.setEnabled(condicao);    
        txt_nome_cli.setEnabled(condicao);
        txt_end_cli.setEnabled(condicao);
        txt_bairro_cli.setEnabled(condicao);
        txt_cidade_cli.setEnabled(condicao);
        cbb_uf_cli.setEnabled(condicao);
        txt_cep_cli.setEnabled(condicao);
        txt_tel_cli.setEnabled(condicao);
    }
    
     //LIMPAR CAMPOS
    private void limparCampos(){
        txt_cod_cli.setText("");
        txt_nome_cli.setText("");
        txt_end_cli.setText("");
        txt_bairro_cli.setText("");
        txt_cidade_cli.setText("");        
        txt_cep_cli.setText("");
        txt_tel_cli.setText("");
    }
    
    //CARREGA DADOS DO BANCO NA TABELA
    private void carregarCliente(){
    listaModelClientes = controllerCliente.getListaclienteController();
    DefaultTableModel modelo = (DefaultTableModel) tb_cliente.getModel();
    modelo.setNumRows(0);
    // Inserir clientes na tabela clientes
    int cont = listaModelClientes.size();     
    for (int i = 0; i < cont; i++){
            
            modelo.addRow(new Object[]{
            listaModelClientes.get(i).getId_cliente(),
            listaModelClientes.get(i).getNome_cli(), 
            listaModelClientes.get(i).getCidade_cli(),
            listaModelClientes.get(i).getUf_cli(),
            listaModelClientes.get(i).getTelefone_cli()
            });  
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar_cli;
    private javax.swing.JButton btn_cancelar_cli;
    private javax.swing.JButton btn_excluir_cli;
    private javax.swing.JButton btn_novo_cli;
    private javax.swing.JButton btn_salvar_cli;
    private javax.swing.JComboBox<String> cbb_uf_cli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_cliente;
    private javax.swing.JTextField txt_bairro_cli;
    private javax.swing.JFormattedTextField txt_cep_cli;
    private javax.swing.JTextField txt_cidade_cli;
    private javax.swing.JTextField txt_cod_cli;
    private javax.swing.JTextField txt_end_cli;
    private javax.swing.JTextField txt_nome_cli;
    private javax.swing.JFormattedTextField txt_tel_cli;
    // End of variables declaration//GEN-END:variables
}
